export const COLLECTION_DATA = {
  All: [
    {
      id: 1,
      name: "Brodeo Beanie",
      price: 30,
      image: "/collection/all1.png",
      materials: ["100% Recycled Wool", "Organic Cotton Lining"],
      colors: ["Orange", "Black", "Navy", "Gray Heather", "Natural"],
      sizes: ["S", "M", "L"],
      description: "A warm and stylish beanie made from recycled wool.",
      rating: 4.7,
    },
    {
      id: 2,
      name: "Riverside Backpack",
      price: 89,
      image: "/collection/all2.png",
      materials: ["Recycled Polyester", "Water-Resistant Coating"],
      colors: ["Black", "Olive", "Navy"],
      sizes: ["One Size"],
      capacity: "28L",
      description:
        "A versatile backpack with ample storage and water resistance.",
      rating: 4.3,
    },
    {
      id: 3,
      name: "Essential Shoulder Bag",
      price: 45,
      image: "/collection/all3.png",
      materials: ["Durable Woven Fabric", "Polyester Blend"],
      colors: ["Black", "Emerald", "Turquoise", "Light Gray", "Dusty Pink"],
      sizes: ["One Size"],
      capacity: "8L",
      features: [
        "Adjustable Strap",
        "Zippered Main Compartment",
        "Embroidered Logo",
      ],
      description: "A compact shoulder bag perfect for daily essentials.",
      rating: 4.1,
    },

    {
      id: 4,
      name: "Alpine Crew Tee",
      price: 45,
      image: "/collection/all4.png",
      materials: ["100% Organic Cotton", "Fair Trade Certified"],
      colors: ["White", "Black", "Gray", "Navy", "Sage"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "A soft and comfortable crew tee made from organic cotton.",
      rating: 4.0,
    },
    {
      id: 5,
      name: "Mountain Hoodie",
      price: 79,
      image: "/collection/all5.png",
      materials: ["Organic Cotton Fleece", "Recycled Polyester Blend"],
      colors: ["Black", "Gray", "Navy", "Olive"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "A cozy hoodie made from organic cotton fleece.",
      rating: 4.8,
    },
    {
      id: 6,
      name: "Trail Pants",
      price: 89,
      image: "/collection/all6.png",
      materials: ["Recycled Nylon", "DWR Finish"],
      colors: ["Black", "Khaki", "Navy", "Olive"],
      sizes: ["28", "30", "32", "34", "36"],
      description: "Durable trail pants with a water-repellent finish.",
      rating: 4.6,
    },
    {
      id: 7,
      name: "Summit Beanie",
      price: 29,
      image: "/collection/all7.png",
      materials: ["Merino Wool Blend", "Recycled Polyester"],
      colors: ["Black", "Gray", "Navy", "Forest"],
      sizes: ["One Size"],
      description: "A warm beanie made from a merino wool blend.",
      rating: 4.5,
    },
    {
      id: 8,
      name: "Crest Vest",
      price: 119,
      image: "/collection/all8.png",
      materials: ["Recycled Polyester", "DWR Finish"],
      colors: ["Black", "Gray", "Navy", "Olive"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "A lightweight and warm vest for outdoor adventures.",
      rating: 4.8,
    },
  ],
  Shorts: [
    {
      id: 9,
      name: "Trail Shorts",
      price: 45,
      image: "",
      materials: ["Recycled Polyester", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      description: "Durable and comfortable shorts for trail activities.",
      rating: 4.4,
    },
    {
      id: 10,
      name: "Adventure Shorts",
      price: 55,
      image: "",
      materials: ["Organic Cotton", "Stretch Fabric"],
      colors: ["Khaki", "Olive", "Navy"],
      sizes: ["S", "M", "L", "XL"],
      description: "Stretchable shorts designed for adventure and comfort.",
      rating: 4.5,
    },
    {
      id: 11,
      name: "Sample Shorts",
      price: 89,
      image: "",
      materials: ["Sample Cotton", "Sample Fabric"],
      colors: ["Khaki", "Olive", "Navy", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      description: "Sample shorts with a unique design and fabric.",
      rating: 4.3,
    },
    {
      id: 12,
      name: "Sample Shorts",
      price: 89,
      image: "",
      materials: ["Sample Cotton", "Sample Fabric"],
      colors: ["Khaki", "Olive", "Navy", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      description: "Sample shorts with a unique design and fabric.",
      rating: 4.3,
    },
    {
      id: 13,
      name: "Sample Shorts",
      price: 89,
      image: "",
      materials: ["Sample Cotton", "Sample Fabric"],
      colors: ["Khaki", "Olive", "Navy", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      description: "Sample shorts with a unique design and fabric.",
      rating: 4.3,
    },
    {
      id: 14,
      name: "Sample Shorts",
      price: 89,
      image: "",
      materials: ["Sample Cotton", "Sample Fabric"],
      colors: ["Khaki", "Olive", "Navy", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      description: "Sample shorts with a unique design and fabric.",
      rating: 4.3,
    },
    {
      id: 15,
      name: "Sample Shorts",
      price: 89,
      image: "",
      materials: ["Sample Cotton", "Sample Fabric"],
      colors: ["Khaki", "Olive", "Navy", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      description: "Sample shorts with a unique design and fabric.",
      rating: 4.3,
    },
    {
      id: 16,
      name: "Sample Shorts",
      price: 89,
      image: "",
      materials: ["Sample Cotton", "Sample Fabric"],
      colors: ["Khaki", "Olive", "Navy", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      description: "Sample shorts with a unique design and fabric.",
      rating: 4.3,
    },
  ],
  Jackets: [
    {
      id: 17,
      name: "Explorer Jacket",
      price: 150,
      image: "",
      materials: ["Recycled Polyester", "Thermal Insulation"],
      colors: ["Black", "Forest Green", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "A warm and insulated jacket for exploring the outdoors.",
      rating: 4.9,
    },
    {
      id: 18,
      name: "Windbreaker Jacket",
      price: 99,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "A lightweight windbreaker with water-repellent finish.",
      rating: 4.6,
    },
    {
      id: 19,
      name: "Sample Jacket",
      price: 133,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Sample jacket with a stylish design and water resistance.",
      rating: 4.2,
    },
    {
      id: 20,
      name: "Sample Jacket",
      price: 133,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Sample jacket with a stylish design and water resistance.",
      rating: 4.2,
    },
    {
      id: 21,
      name: "Sample Jacket",
      price: 133,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Sample jacket with a stylish design and water resistance.",
      rating: 4.2,
    },
    {
      id: 22,
      name: "Sample Jacket",
      price: 133,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Sample jacket with a stylish design and water resistance.",
      rating: 4.2,
    },
    {
      id: 23,
      name: "Sample Jacket",
      price: 133,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Sample jacket with a stylish design and water resistance.",
      rating: 4.2,
    },
    {
      id: 24,
      name: "Sample Jacket",
      price: 133,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Sample jacket with a stylish design and water resistance.",
      rating: 4.2,
    },
  ],
  Shoes: [
    {
      id: 25,
      name: "Hiking Shoes",
      price: 110,
      image: "",
      materials: ["Waterproof Mesh", "Vibram Sole"],
      colors: ["Black", "Gray", "Brown"],
      sizes: ["8", "9", "10", "11", "12"],
      description: "Durable hiking shoes with waterproof mesh and Vibram sole.",
      rating: 4.6,
    },
    {
      id: 26,
      name: "Trail Runners",
      price: 95,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Lightweight trail runners with breathable mesh.",
      rating: 4.5,
    },
    {
      id: 27,
      name: "Sample Shoes",
      price: 69,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Sample shoes with a comfortable and breathable design.",
      rating: 4.1,
    },
    {
      id: 28,
      name: "Sample Shoes",
      price: 69,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Sample shoes with a comfortable and breathable design.",
      rating: 4.1,
    },
    {
      id: 29,
      name: "Sample Shoes",
      price: 69,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Sample shoes with a comfortable and breathable design.",
      rating: 4.1,
    },
    {
      id: 30,
      name: "Sample Shoes",
      price: 69,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Sample shoes with a comfortable and breathable design.",
      rating: 4.1,
    },
    {
      id: 31,
      name: "Sample Shoes",
      price: 69,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Sample shoes with a comfortable and breathable design.",
      rating: 4.1,
    },
    {
      id: 32,
      name: "Sample Shoes",
      price: 69,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
      description: "Sample shoes with a comfortable and breathable design.",
      rating: 4.1,
    },
  ],
  "T-shirt": [
    {
      id: 33,
      name: "Alpine Crew Tee",
      price: 45,
      image: "",
      materials: ["100% Organic Cotton", "Fair Trade Certified"],
      colors: ["White", "Black", "Gray", "Navy", "Sage"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "A soft and comfortable crew tee made from organic cotton.",
      rating: 4.7,
    },
    {
      id: 34,
      name: "Graphic T-Shirt",
      price: 30,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "A stylish graphic t-shirt made from organic cotton.",
      rating: 4.5,
    },
    {
      id: 35,
      name: "Sample T-Shirt",
      price: 25,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Sample t-shirt with a simple and classic design.",
      rating: 4.0,
    },
    {
      id: 36,
      name: "Sample T-Shirt",
      price: 25,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Sample t-shirt with a simple and classic design.",
      rating: 4.0,
    },
    {
      id: 37,
      name: "Sample T-Shirt",
      price: 25,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Sample t-shirt with a simple and classic design.",
      rating: 4.0,
    },
    {
      id: 38,
      name: "Sample T-Shirt",
      price: 25,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Sample t-shirt with a simple and classic design.",
      rating: 4.0,
    },
    {
      id: 39,
      name: "Sample T-Shirt",
      price: 25,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Sample t-shirt with a simple and classic design.",
      rating: 4.0,
    },
    {
      id: 40,
      name: "Sample T-Shirt",
      price: 25,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      description: "Sample t-shirt with a simple and classic design.",
      rating: 4.0,
    },
  ],
};
