export const COLLECTION_DATA = {
  All: [
    {
      name: "Brodeo Beanie",
      price: 25,
      image: "/collection/all1.png",
      materials: ["100% Recycled Wool", "Organic Cotton Lining"],
      colors: ["Orange", "Black", "Navy", "Gray Heather", "Natural"],
      sizes: ["S", "M", "L"],
    },
    {
      name: "Riverside Backpack",
      price: 89,
      image: "/collection/all2.png",
      materials: ["Recycled Polyester", "Water-Resistant Coating"],
      colors: ["Black", "Olive", "Navy"],
      sizes: ["One Size"],
      capacity: "28L",
    },
    {
      name: "Essential Shoulder Bag",
      price: 45,
      image: "/collection/all3.png",
      materials: ["Durable Woven Fabric", "Polyester Blend"],
      colors: ["Black", "Emerald", "Turquoise", "Light Gray", "Dusty Pink"],
      sizes: ["One Size"],
      capacity: "8L",
      features: [
        "Adjustable Strap",
        "Zippered Main Compartment",
        "Embroidered Logo",
      ],
    },

    {
      name: "Alpine Crew Tee",
      price: 45,
      image: "/collection/all4.png",
      materials: ["100% Organic Cotton", "Fair Trade Certified"],
      colors: ["White", "Black", "Gray", "Navy", "Sage"],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
    {
      name: "Mountain Hoodie",
      price: 79,
      image: "/collection/all5.png",
      materials: ["Organic Cotton Fleece", "Recycled Polyester Blend"],
      colors: ["Black", "Gray", "Navy", "Olive"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Trail Pants",
      price: 89,
      image: "/collection/all6.png",
      materials: ["Recycled Nylon", "DWR Finish"],
      colors: ["Black", "Khaki", "Navy", "Olive"],
      sizes: ["28", "30", "32", "34", "36"],
    },
    {
      name: "Summit Beanie",
      price: 29,
      image: "/collection/all7.png",
      materials: ["Merino Wool Blend", "Recycled Polyester"],
      colors: ["Black", "Gray", "Navy", "Forest"],
      sizes: ["One Size"],
    },
    {
      name: "Crest Vest",
      price: 119,
      image: "/collection/all8.png",
      materials: ["Recycled Polyester", "DWR Finish"],
      colors: ["Black", "Gray", "Navy", "Olive"],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
  ],
  Shorts: [
    {
      name: "Trail Shorts",
      price: 45,
      image: "",
      materials: ["Recycled Polyester", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Adventure Shorts",
      price: 55,
      image: "",
      materials: ["Organic Cotton", "Stretch Fabric"],
      colors: ["Khaki", "Olive", "Navy"],
      sizes: ["S", "M", "L", "XL"],
    },
  ],
  Jackets: [
    {
      name: "Explorer Jacket",
      price: 150,
      image: "",
      materials: ["Recycled Polyester", "Thermal Insulation"],
      colors: ["Black", "Forest Green", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
    {
      name: "Windbreaker Jacket",
      price: 99,
      image: "",
      materials: ["Recycled Nylon", "Water-Repellent Finish"],
      colors: ["Black", "Gray", "Navy", "Red"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
  Shoes: [
    {
      name: "Hiking Shoes",
      price: 110,
      image: "",
      materials: ["Waterproof Mesh", "Vibram Sole"],
      colors: ["Black", "Gray", "Brown"],
      sizes: ["8", "9", "10", "11", "12"],
    },
    {
      name: "Trail Runners",
      price: 95,
      image: "",
      materials: ["Breathable Mesh", "Recycled Rubber"],
      colors: ["Black", "Navy", "Olive"],
      sizes: ["7", "8", "9", "10", "11", "12"],
    },
  ],
  "T-shirt": [
    {
      name: "Alpine Crew Tee",
      price: 45,
      image: "",
      materials: ["100% Organic Cotton", "Fair Trade Certified"],
      colors: ["White", "Black", "Gray", "Navy", "Sage"],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
    {
      name: "Graphic T-Shirt",
      price: 30,
      image: "",
      materials: ["100% Organic Cotton"],
      colors: ["White", "Black", "Gray", "Navy"],
      sizes: ["XS", "S", "M", "L", "XL"],
    },
  ],
};
